return {
    Drawable = {
        [0] = "face",
        [1] = "masks",
        [2] = "hair",
        [3] = "torsos",
        [4] = "legs",
        [5] = "bags",
        [6] = "shoes",
        [7] = "neck",
        [8] = "shirts",
        [9] = "vest",
        [10] = "decals",
        [11] = "jackets"
    },
    Props = {
        [0] = "hats",
        [1] = "glasses",
        [2] = "earrings",
        [3] = "mouth",
        [4] = "lhand",
        [5] = "rhand",
        [6] = "watches",
        [7] = "bracelets",
    },
    FaceFeatures = {
        [0] = "Nose_Width",
        [1] = "Nose_Peak_Height",
        [2] = "Nose_Peak_Length",
        [3] = "Nose_Bone_Height",
        [4] = "Nose_Peak_Lowering",
        [5] = "Nose_Bone_Twist",
        [6] = "EyeBrow_Height",
        [7] = "EyeBrow_Forward",
        [8] = "Cheeks_Bone_High",
        [9] = "Cheeks_Bone_Width",
        [10] = "Cheeks_Width",
        [11] = "Eyes_Openning",
        [12] = "Lips_Thickness",
        [13] = "Jaw_Bone_Width",
        [14] = "Jaw_Bone_Back_Length",
        [15] = "Chin_Bone_Lowering",
        [16] = "Chin_Bone_Length",
        [17] = "Chin_Bone_Width",
        [18] = "Chin_Hole",
        [19] = "Neck_Thickness"
    },
    Head = {
        [0] = "Blemishes",
        [1] = "FacialHair",
        [2] = "Eyebrows",
        [3] = "Ageing",
        [4] = "Makeup",
        [5] = "Blush",
        [6] = "Complexion",
        [7] = "SunDamage",
        [8] = "Lipstick",
        [9] = "MolesFreckles",
        [10] = "ChestHair",
        [11] = "BodyBlemishes",
        [12] = "AddBodyBlemishes",
        [13] = "EyeColour"
    }
}