-- =============================================================
--  jp-lunar_fishing - QBCore 用アイテム定義（日本語ラベル）
-- =============================================================
--
--  使い方:
--  qb-core/shared/items.lua の QBShared.Items = { ... } ブロックの
--  中に、下記の各エントリを追記してください。
--
--  画像配置:
--  assets/fish_images/ 配下の PNG を、qb-inventory/html/images/
--  （または使用しているインベントリの画像ディレクトリ）にコピーして
--  ください。ファイル名はキーと完全一致、小文字、拡張子 .png。
--
--  ライセンス: GPL-3.0（jp-lunar_fishing 全体に従う）
-- =============================================================

-- ===== 魚（10種） =====
['iwashi'] = {
    ['name']        = 'iwashi',
    ['label']       = 'イワシ',
    ['weight']      = 100,
    ['type']        = 'item',
    ['image']       = 'iwashi.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '日本近海で最も馴染み深い小魚。安価だが数が稼げる。',
},
['aji'] = {
    ['name']        = 'aji',
    ['label']       = 'アジ',
    ['weight']      = 150,
    ['type']        = 'item',
    ['image']       = 'aji.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '回遊魚。塩焼きや刺身で親しまれる定番魚。',
},
['saba'] = {
    ['name']        = 'saba',
    ['label']       = 'サバ',
    ['weight']      = 200,
    ['type']        = 'item',
    ['image']       = 'saba.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '青魚の代表格。脂が乗っていて市場価値も安定している。',
},
['tai'] = {
    ['name']        = 'tai',
    ['label']       = 'マダイ',
    ['weight']      = 500,
    ['type']        = 'item',
    ['image']       = 'tai.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '祝い事に欠かせない高級魚。沿岸でも釣れる。',
},
['hirame'] = {
    ['name']        = 'hirame',
    ['label']       = 'ヒラメ',
    ['weight']      = 600,
    ['type']        = 'item',
    ['image']       = 'hirame.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = 'サンゴ礁の砂地に潜む高級白身魚。',
},
['unagi'] = {
    ['name']        = 'unagi',
    ['label']       = 'ウナギ',
    ['weight']      = 400,
    ['type']        = 'item',
    ['image']       = 'unagi.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '沼地や淡水域に潜む。ぬめりが強く扱いが難しい。',
},
['buri'] = {
    ['name']        = 'buri',
    ['label']       = 'ブリ',
    ['weight']      = 800,
    ['type']        = 'item',
    ['image']       = 'buri.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '出世魚として知られる大型の回遊魚。脂の乗りが絶品。',
},
['katsuo'] = {
    ['name']        = 'katsuo',
    ['label']       = 'カツオ',
    ['weight']      = 1000,
    ['type']        = 'item',
    ['image']       = 'katsuo.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '黒潮に乗って回遊する高速魚。たたきは日本の伝統料理。',
},
['maguro'] = {
    ['name']        = 'maguro',
    ['label']       = 'クロマグロ',
    ['weight']      = 3000,
    ['type']        = 'item',
    ['image']       = 'maguro.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '深海を泳ぐ高級魚の王様。市場で高値が付く。',
},
['ryugu'] = {
    ['name']        = 'ryugu',
    ['label']       = 'リュウグウノツカイ',
    ['weight']      = 2000,
    ['type']        = 'item',
    ['image']       = 'ryugu.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '深海に棲む幻の魚。古来より竜宮の使いと呼ばれる。',
},

-- ===== 釣り竿（3種） =====
['basic_rod'] = {
    ['name']        = 'basic_rod',
    ['label']       = '初心者の釣り竿',
    ['weight']      = 1500,
    ['type']        = 'item',
    ['image']       = 'basic_rod.png',
    ['unique']      = false,
    ['useable']     = true,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '入門用の釣り竿。耐久性は低いが安価。',
},
['graphite_rod'] = {
    ['name']        = 'graphite_rod',
    ['label']       = 'グラファイト竿',
    ['weight']      = 1200,
    ['type']        = 'item',
    ['image']       = 'graphite_rod.png',
    ['unique']      = false,
    ['useable']     = true,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '軽くてしなやかな中級者向け釣り竿。',
},
['titanium_rod'] = {
    ['name']        = 'titanium_rod',
    ['label']       = 'チタン竿',
    ['weight']      = 1000,
    ['type']        = 'item',
    ['image']       = 'titanium_rod.png',
    ['unique']      = false,
    ['useable']     = true,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '高剛性のプロ仕様釣り竿。ほとんど折れない。',
},

-- ===== 餌（2種） =====
['worms'] = {
    ['name']        = 'worms',
    ['label']       = 'ミミズ',
    ['weight']      = 50,
    ['type']        = 'item',
    ['image']       = 'worms.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '定番の生き餌。万能だが特別な誘引力はない。',
},
['artificial_bait'] = {
    ['name']        = 'artificial_bait',
    ['label']       = 'ルアー',
    ['weight']      = 30,
    ['type']        = 'item',
    ['image']       = 'artificial_bait.png',
    ['unique']      = false,
    ['useable']     = false,
    ['shouldClose'] = true,
    ['combinable']  = nil,
    ['description'] = '人工餌。釣り時間を大幅に短縮できる。',
},
