local function register(name, serverEvent)
  RegisterNUICallback(name, function(body, cb)
    TriggerServerEvent(serverEvent, body or {})
    cb({ ok = true, forwarded = true })
  end)
end

register('session_enter', 'refboard:session:enter')
register('session_leave', 'refboard:session:leave')
register('lock_acquire', 'refboard:lock:acquire')
register('lock_release', 'refboard:lock:release')
register('lock_heartbeat', 'refboard:lock:heartbeat')
register('team_list', 'refboard:team:list')
register('match_list', 'refboard:match:list')
register('match_create', 'refboard:match:create')
register('autosave_draft', 'refboard:autosave:draft')
register('match_get', 'refboard:match:get')
register('match_checkResume', 'refboard:match:checkResume')
register('match_finish', 'refboard:match:finish')
register('match_reopen', 'refboard:match:reopen')
register('score_goal', 'refboard:score:goal')
register('score_manual_edit', 'refboard:score:manual_edit')
register('player_resolve', 'refboard:player:resolve')
register('player_add', 'refboard:player:add')
register('player_online_list', 'refboard:player:online_list')
register('presence_list', 'refboard:presence:list')
register('presence_focus', 'refboard:presence:focus')
register('match_set_half', 'refboard:match:set_half')
register('event_substitute', 'refboard:event:substitute')
register('event_issue_card', 'refboard:event:issue_card')
register('event_record_penalty', 'refboard:event:record_penalty')
