import DOMPurify from 'dompurify'

/** ヘルプ Markdown（marked 出力）向け。script / iframe / on* を確実に除外しつつ一般的な記法を許可 */
const HELP_HTML_CONFIG = {
  ALLOWED_TAGS: [
    'a',
    'abbr',
    'b',
    'blockquote',
    'br',
    'caption',
    'code',
    'col',
    'colgroup',
    'dd',
    'del',
    'details',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'i',
    'img',
    'ins',
    'kbd',
    'li',
    'mark',
    'ol',
    'p',
    'pre',
    'q',
    'rp',
    'rt',
    'ruby',
    's',
    'samp',
    'small',
    'span',
    'strong',
    'sub',
    'sup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'time',
    'tr',
    'ul',
    'var',
    'wbr',
  ],
  ALLOWED_ATTR: [
    'href',
    'title',
    'class',
    'id',
    'colspan',
    'rowspan',
    'start',
    'reversed',
    'src',
    'alt',
    'width',
    'height',
    'loading',
    'decoding',
  ],
  ALLOW_DATA_ATTR: false,
  FORBID_TAGS: ['script', 'style', 'iframe', 'object', 'embed', 'form', 'input', 'button', 'svg', 'math'],
  FORBID_ATTR: [
    'onerror',
    'onload',
    'onclick',
    'onmouseover',
    'onfocus',
    'onblur',
    'onmouseout',
    'oninput',
    'onkeydown',
    'onkeyup',
  ],
}

export function sanitizeHelpHtml(dirty: string): string {
  return String(DOMPurify.sanitize(dirty, HELP_HTML_CONFIG))
}
