--- カードマスタ（起動時に DB へ UPSERT。数値は1〜10）
--- image_path は NUI 基準（html/ からの相対）。実ファイル: html/assets/cards/{character|monster}/
--- キャラ 20（character/*.jpg・card_id ベースファイル名）+ モンスター tcg_m_* 21 = 計 41（no 1〜41）。type は shitei / free（tcg_m_* は card_id で識別）
--- 合計の目安: UR 28〜32, SS 24〜27, S 20〜23, A 16〜19, B 12〜15, C 8〜11
--- name_en / description_en: BOOK NUI 英語表示用（DB 列にシードされる）
TcgCardsMaster = {
    {
        card_id = 'tcg_ur_antares',
        name = '覇星アンタレス',
        name_en = 'Antares the Sovereign Star',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 8,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ur_antares.jpg',
        description = '四方位にほぼ隙がない絶対王者。デッキの柱に据えたい。',
        description_en = 'Nearly flawless on all four sides—the backbone of your deck.',
        no = 1,
    },
    {
        card_id = 'tcg_ur_void_edge',
        name = '虚空の刃鬼',
        name_en = 'Void Blade Oni',
        rank = 'UR',
        type = 'shitei',
        stat_top = 6,
        stat_right = 10,
        stat_bottom = 5,
        stat_left = 9,
        image_path = 'assets/cards/character/tcg_ur_void_edge.jpg',
        description = '右辺と左辺に極大火力。配置で脅威の脅威帯を形成する。',
        description_en = 'Huge power on left and right—placement builds a brutal horizontal threat.',
        no = 2,
    },
    {
        card_id = 'tcg_ss_silver_knight',
        name = '銀翼の聖騎士',
        name_en = 'Silverwing Paladin',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_ss_silver_knight.jpg',
        description = '上方向への突破力が高く、先攻配置に向く。',
        description_en = 'Strong upward punch—great when you place first.',
        no = 3,
    },
    {
        card_id = 'tcg_ss_moon_sage',
        name = '月虹の賢者',
        name_en = 'Moonbow Sage',
        rank = 'SS',
        type = 'shitei',
        stat_top = 6,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ss_moon_sage.jpg',
        description = '下・左を厚くし、盤面下角の確保に強い。',
        description_en = 'Thick toward bottom-left—locks down the lower corner.',
        no = 4,
    },
    {
        card_id = 'tcg_s_flame_fist',
        name = '烈火の拳士',
        name_en = 'Blazing Pugilist',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_s_flame_fist.jpg',
        description = '攻め寄りのバランス。上・右でプレッシャーをかける。',
        description_en = 'Aggressive balance—applies pressure from the top and right.',
        no = 5,
    },
    {
        card_id = 'tcg_s_aqua_shield',
        name = '深水の盾艇',
        name_en = 'Deepwater Bulwark',
        rank = 'S',
        type = 'free',
        stat_top = 5,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_s_aqua_shield.jpg',
        description = '下方向をやや厚くした防衛型。',
        description_en = 'Slightly thicker downward—leans defensive.',
        no = 6,
    },
    {
        card_id = 'tcg_s_wind_runner',
        name = '疾風の斥候',
        name_en = 'Galewind Scout',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_s_wind_runner.jpg',
        description = '機動力重視。上辺からの奇襲に。',
        description_en = 'Mobility-focused—strikes along the top edge.',
        no = 7,
    },
    {
        card_id = 'tcg_s_stone_wall',
        name = '磐石の守人',
        name_en = 'Bedrock Warden',
        rank = 'S',
        type = 'free',
        stat_top = 4,
        stat_right = 8,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_s_stone_wall.jpg',
        description = '右辺特化の盾。横並びの奪取に強い。',
        description_en = 'Right-side shield—strong in sideways trades.',
        no = 8,
    },
    {
        card_id = 'tcg_a_iron_spike',
        name = '鉄棘の番人',
        name_en = 'Iron Thorn Sentinel',
        rank = 'A',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_a_iron_spike.jpg',
        description = '堅実なオールラウンダー。',
        description_en = 'Reliable all-rounder.',
        no = 9,
    },
    {
        card_id = 'tcg_a_shadow_cat',
        name = '影歩きの猫盗賊',
        name_en = 'Shadowstep Cat Thief',
        rank = 'A',
        type = 'free',
        stat_top = 6,
        stat_right = 4,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_a_shadow_cat.jpg',
        description = '上と左右のバランス取り。隙を突く動き向き。',
        description_en = 'Balanced top and sides—looks for angles.',
        no = 10,
    },
    {
        card_id = 'tcg_a_holy_moth',
        name = '燐火の聖蛾',
        name_en = 'Witchfire Holy Moth',
        rank = 'A',
        type = 'free',
        stat_top = 4,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_a_holy_moth.jpg',
        description = '右への伸びで軽く有利を取る。',
        description_en = 'Reaches right for a slight advantage.',
        no = 11,
    },
    {
        card_id = 'tcg_a_rust_golem',
        name = '錆鉄の小ゴーレム',
        name_en = 'Rustiron Golemling',
        rank = 'A',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_a_rust_golem.jpg',
        description = '地味だが角で事故を減らす。',
        description_en = 'Plain but helps avoid corner disasters.',
        no = 12,
    },
    {
        card_id = 'tcg_b_moss_sprite',
        name = '苔森のスプライト',
        name_en = 'Mossgrove Sprite',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_moss_sprite.jpg',
        description = '完全バランスの凡庸カード。',
        description_en = 'Perfectly even stats—a filler staple.',
        no = 13,
    },
    {
        card_id = 'tcg_b_cave_bat',
        name = '洞窟コウモリ',
        name_en = 'Cavern Bat',
        rank = 'B',
        type = 'free',
        stat_top = 5,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_cave_bat.jpg',
        description = '上だけ突出した奇襲役。',
        description_en = 'Top-heavy surprise striker.',
        no = 14,
    },
    {
        card_id = 'tcg_b_mud_frog',
        name = '泥沼ガエル',
        name_en = 'Mire Frog',
        rank = 'B',
        type = 'free',
        stat_top = 3,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_mud_frog.jpg',
        description = '右に振った火力。',
        description_en = 'Power shifted to the right.',
        no = 15,
    },
    {
        card_id = 'tcg_b_coal_imp',
        name = '炭坑インプ',
        name_en = 'Colliery Imp',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 3,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_coal_imp.jpg',
        description = '下が弱め。上でつなぐ前提。',
        description_en = 'Weak below—plan to link from the top.',
        no = 16,
    },
    {
        card_id = 'tcg_c_slime',
        name = 'グリーンスライム',
        name_en = 'Green Slime',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 3,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_slime.jpg',
        description = 'どこも強くないが敷き詰めやすい。',
        description_en = 'Nowhere strong—easy slot filler.',
        no = 17,
    },
    {
        card_id = 'tcg_c_rat',
        name = '溝ネズミ',
        name_en = 'Gutter Rat',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 3,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_rat.jpg',
        description = '上が弱い。下レーンでのつなぎ用。',
        description_en = 'Soft on top—bridging piece for the bottom lane.',
        no = 18,
    },
    {
        card_id = 'tcg_c_mushroom',
        name = '歩くキノコ',
        name_en = 'Walking Mushroom',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 2,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_mushroom.jpg',
        description = '右が穴場。逆に右からは狙われやすい。',
        description_en = 'Weak on the right—watch for attacks from that side.',
        no = 19,
    },
    {
        card_id = 'tcg_c_ghost_jelly',
        name = '幽霊クラゲ',
        name_en = 'Ghost Jelly',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 2,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_ghost_jelly.jpg',
        description = '下・左にわずかな粘り。',
        description_en = 'A little staying power on bottom-left.',
        no = 20,
    },
    {
        card_id = 'tcg_m_ur_reaper',
        name = '冥府の死神司祭ターナトス',
        name_en = 'Thanatos, High Priest of the Underworld',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 9,
        stat_left = 9,
        image_path = 'assets/cards/monster/tcg_m_ur_reaper.jpg',
        description = '紫炎を纏う大鎌で魂を刈り取る冥府の使徒。彼の通った跡には霊魂すら残らない。',
        description_en = 'An emissary of the underworld who reaps souls with a violet-flamed scythe. Not even spirits remain in his wake.',
        no = 21,
    },
    {
        card_id = 'tcg_m_ur_moon_goddess',
        name = '月夜の女神セレネ',
        name_en = 'Selene, Goddess of the Moonlit Night',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 9,
        stat_bottom = 8,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_ur_moon_goddess.jpg',
        description = '三日月の冠を戴き、銀の月杖で潮汐と夢を司る女神。月光の下で全ての傷は癒される。',
        description_en = 'A goddess crowned with the crescent, ruling tides and dreams with her silver moon-staff. All wounds are healed beneath her moonlight.',
        no = 22,
    },
    {
        card_id = 'tcg_m_ss_thunder_god',
        name = '雷霆神トールヴァル',
        name_en = 'Thorvall, God of Thunder',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_thunder_god.jpg',
        description = '白髭をなびかせ黄金鎧を纏う雷神。振り下ろす雷鎚は山を割り、嵐を呼ぶ。',
        description_en = 'A thunder god in golden armor with a billowing white beard. His descending hammer cleaves mountains and summons storms.',
        no = 23,
    },
    {
        card_id = 'tcg_m_ss_phoenix',
        name = '鎖縛の不死鳥イグニス',
        name_en = 'Ignis, the Chained Phoenix',
        rank = 'SS',
        type = 'shitei',
        stat_top = 8,
        stat_right = 8,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_phoenix.jpg',
        description = '黒鎧と鎖で力を封じられた炎の霊鳥。死しても灰から蘇り、千年の業火を撒き散らす。',
        description_en = 'A flame-spirit bird whose power is sealed by black armor and chains. Though slain, she rises from ashes to scatter a thousand-year inferno.',
        no = 24,
    },
    {
        card_id = 'tcg_m_ss_sea_goddess',
        name = '珊瑚の海神アクアリーネ',
        name_en = 'Aquarine, Goddess of the Coral Seas',
        rank = 'SS',
        type = 'shitei',
        stat_top = 7,
        stat_right = 8,
        stat_bottom = 7,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_ss_sea_goddess.jpg',
        description = '珊瑚の冠と貝殻の鎧を纏い、サンゴ三叉戟で潮流を操る海の女神。船乗りの祈りを聞き届ける。',
        description_en = 'A sea goddess in coral crown and shell armor, commanding currents with her coral trident. She heeds the prayers of sailors.',
        no = 25,
    },
    {
        card_id = 'tcg_m_s_sun_priest',
        name = '黄金の太陽神官ソルアレス',
        name_en = 'Solares, Priest of the Golden Sun',
        rank = 'S',
        type = 'free',
        stat_top = 8,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_s_sun_priest.jpg',
        description = '黄金の鎧と白マントを纏い炎槍を掲げる神官。彼が槍を天に向ければ太陽が応える。',
        description_en = 'A priest in golden armor and white mantle, raising a flame-spear. When he points it skyward, the sun answers his call.',
        no = 26,
    },
    {
        card_id = 'tcg_m_s_pharaoh_mummy',
        name = '古王国のファラオ・ミイラ',
        name_en = 'Pharaoh Mummy of the Old Kingdom',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_pharaoh_mummy.jpg',
        description = '青き炎の眼でアンク杖を握る王のミイラ。聖刻文字の呪いは三千年の時を超えて生者を縛る。',
        description_en = 'A royal mummy with eyes of blue flame, gripping an ankh-staff. His hieroglyphic curse binds the living across three millennia.',
        no = 27,
    },
    {
        card_id = 'tcg_m_s_dark_witch',
        name = '暗黒の角持ち魔女モルガナ',
        name_en = 'Morgana, the Horned Dark Witch',
        rank = 'S',
        type = 'free',
        stat_top = 8,
        stat_right = 7,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_dark_witch.jpg',
        description = '黒髪に角を生やし髑髏杖を振るう魔女。紫炎の呪文は敵の影を縫い止め、抜け出させない。',
        description_en = 'A witch with black hair and horns, brandishing a skull-staff. Her violet-flame hex pins enemies by their own shadows.',
        no = 28,
    },
    {
        card_id = 'tcg_m_s_forest_spirit',
        name = '深森の樹霊フローラ',
        name_en = 'Flora, Spirit of the Deep Forest',
        rank = 'S',
        type = 'free',
        stat_top = 6,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_s_forest_spirit.jpg',
        description = '緑髪に花冠、蝶を従える森の精霊。彼女が踏みしめた地には一夜で花が咲き乱れる。',
        description_en = 'A forest spirit with green hair, a flower crown, and butterflies in her train. Where she steps, blossoms bloom in a single night.',
        no = 29,
    },
    {
        card_id = 'tcg_m_a_demon_warlord',
        name = '赤肌の魔将バルガス',
        name_en = 'Balgus, the Crimson Warlord',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_a_demon_warlord.jpg',
        description = '赤き肌に巻角を持つ魔族の将。両手大斧の一振りは、敵陣の隊列ごと薙ぎ払う。',
        description_en = 'A demon warlord with crimson skin and curling horns. A single swing of his great axe sweeps away entire battle lines.',
        no = 30,
    },
    {
        card_id = 'tcg_m_a_blood_berserker',
        name = '血染めの戦鬼ガルム',
        name_en = 'Garm, the Blood-Soaked Berserker',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_a_blood_berserker.jpg',
        description = '烏旗を背負い双剣で踊るように戦う狂戦士。返り血を浴びるほど剣速が増す。',
        description_en = 'A berserker who dances with twin blades beneath a raven banner. The more blood he is bathed in, the faster his swords become.',
        no = 31,
    },
    {
        card_id = 'tcg_m_a_flame_valkyrie',
        name = '紅蓮の戦姫イグニフィア',
        name_en = 'Ignifia, the Crimson Valkyrie',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_a_flame_valkyrie.jpg',
        description = '赤髪と紅鎧を纏い双炎刀を振るう戦姫。彼女の通った戦場は灰しか残らない。',
        description_en = 'A valkyrie in crimson armor with flowing red hair, wielding twin flame-blades. Only ashes remain on the battlefield she crosses.',
        no = 32,
    },
    {
        card_id = 'tcg_m_a_medusa',
        name = '蛇髪の魔女メデューサ',
        name_en = 'Medusa, the Serpent-Haired Witch',
        rank = 'A',
        type = 'free',
        stat_top = 6,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_a_medusa.jpg',
        description = '蛇の髪を蠢かせ青銅の曲刀を持つ呪われた美女。その眼を見た者は石となる。',
        description_en = 'A cursed beauty with writhing serpents for hair, gripping a bronze curved blade. Those who meet her gaze are turned to stone.',
        no = 33,
    },
    {
        card_id = 'tcg_m_a_minotaur',
        name = '迷宮の牛頭ミノタウロス',
        name_en = 'Minotaur of the Labyrinth',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_a_minotaur.jpg',
        description = '黒角と棘鎧を纏い両手戦斧を振るう半人半牛の怪物。怒れば迷宮の壁すら砕く。',
        description_en = 'A half-bull beast in black horns and spiked armor, wielding a great battle-axe. In rage, even the labyrinth walls shatter before him.',
        no = 34,
    },
    {
        card_id = 'tcg_m_b_stone_golem',
        name = '古代遺跡のストーンゴーレム',
        name_en = 'Ancient Ruin Stone Golem',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_b_stone_golem.jpg',
        description = '苔生した岩肌に青いルーンを刻まれた巨人。命令を忘れ、千年遺跡を守り続ける。',
        description_en = 'A giant of mossy stone inscribed with glowing blue runes. Long having forgotten its orders, it has guarded the ruins for a thousand years.',
        no = 35,
    },
    {
        card_id = 'tcg_m_b_war_bear',
        name = '戦化粧の熊神獣ウルサ',
        name_en = 'Ursa, the War-Painted Bear-Beast',
        rank = 'B',
        type = 'free',
        stat_top = 6,
        stat_right = 4,
        stat_bottom = 5,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_b_war_bear.jpg',
        description = '骨鎧と赤い戦化粧を纏う熊の神獣。北方部族の守護獣として崇められる。',
        description_en = 'A divine bear-beast in bone armor and red war-paint. The northern tribes revere her as their guardian beast.',
        no = 36,
    },
    {
        card_id = 'tcg_m_b_werewolf',
        name = '満月の人狼ファング',
        name_en = 'Fang, the Full-Moon Werewolf',
        rank = 'B',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_b_werewolf.jpg',
        description = '灰毛に革ベルト、無数の傷跡を持つ獣人。満月の夜のみ理性を失い、最も速くなる。',
        description_en = 'A beastman of grey fur, leather harness, and countless scars. Only on full-moon nights does he lose reason and become his swiftest.',
        no = 37,
    },
    {
        card_id = 'tcg_m_b_crystal_golem',
        name = '蒼晶の核ゴーレム',
        name_en = 'Azure Crystal Core Golem',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_b_crystal_golem.jpg',
        description = '胸の青き核から虹色の光を放つ結晶巨人。砕かれた破片すら攻撃する意志を持つ。',
        description_en = 'A crystal golem emitting rainbow light from the azure core in its chest. Even its shattered shards retain the will to attack.',
        no = 38,
    },
    {
        card_id = 'tcg_m_c_carrion_raven',
        name = '腐肉漁りの大鴉人',
        name_en = 'Carrion-Feasting Ravenfolk',
        rank = 'C',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_c_carrion_raven.jpg',
        description = '赤く濁った眼と皮革の装具を身に着けた鴉人。死体の山を漁って生きる墓場の守人。',
        description_en = 'A ravenfolk with cloudy red eyes and leather harness. He scavenges among corpses, a graveyard\'s unwelcome custodian.',
        no = 39,
    },
    {
        card_id = 'tcg_m_c_armored_slime',
        name = '錆鎧をまとった巨大スライム',
        name_en = 'Rust-Armored Greater Slime',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_c_armored_slime.jpg',
        description = '戦死者の錆びた鎧片を体内に取り込んだ緑色の粘体。柔らかい体は刃を弾き、鎧片は牙となる。',
        description_en = 'A green ooze that has absorbed the rusted armor of fallen warriors. Its soft body deflects blades while the armor shards become its fangs.',
        no = 40,
    },
    {
        card_id = 'tcg_m_c_rot_zombie',
        name = '腐肉の屍喰鬼ロット',
        name_en = 'Rot, the Putrid Ghoul',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_c_rot_zombie.jpg',
        description = '緑灰の腐肉と腫物だらけの屍。垂れ下がった腕で獲物を引き寄せ、伝染性の毒を撒き散らす。',
        description_en = 'A corpse covered in green-grey rot and pustules. With his dangling arms he drags victims close, spreading contagious venom.',
        no = 41,
    },
}
