--- カードマスタ（起動時に DB へ UPSERT。数値は1〜10）
--- image_path は NUI 基準（html/ からの相対）。実ファイル: html/assets/cards/{character|monster}/
--- 割当: 人物・英雄寄り tcg_ch_001〜010 / モンスター寄り tcg_m_001〜010（20枚。素材差し替え時は番号だけ合わせれば可）
--- 合計の目安: UR 28〜32, SS 24〜27, S 20〜23, A 16〜19, B 12〜15, C 8〜11
--- description_en: BOOK NUI 英語表示用（DB 列 description_en にシードされる）
TcgCardsMaster = {
    {
        card_id = 'tcg_ur_antares',
        name = '覇星アンタレス',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 8,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ch_001.png',
        description = '四方位にほぼ隙がない絶対王者。デッキの柱に据えたい。',
        description_en = 'Nearly flawless on all four sides—the backbone of your deck.',
        no = 1,
    },
    {
        card_id = 'tcg_ur_void_edge',
        name = '虚空の刃鬼',
        rank = 'UR',
        type = 'shitei',
        stat_top = 6,
        stat_right = 10,
        stat_bottom = 5,
        stat_left = 9,
        image_path = 'assets/cards/character/tcg_ch_002.png',
        description = '右辺と左辺に極大火力。配置で脅威の脅威帯を形成する。',
        description_en = 'Huge power on left and right—placement builds a brutal horizontal threat.',
        no = 2,
    },
    {
        card_id = 'tcg_ss_silver_knight',
        name = '銀翼の聖騎士',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_ch_003.png',
        description = '上方向への突破力が高く、先攻配置に向く。',
        description_en = 'Strong upward punch—great when you place first.',
        no = 3,
    },
    {
        card_id = 'tcg_ss_moon_sage',
        name = '月虹の賢者',
        rank = 'SS',
        type = 'shitei',
        stat_top = 6,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ch_004.png',
        description = '下・左を厚くし、盤面下角の確保に強い。',
        description_en = 'Thick toward bottom-left—locks down the lower corner.',
        no = 4,
    },
    {
        card_id = 'tcg_s_flame_fist',
        name = '烈火の拳士',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_ch_005.png',
        description = '攻め寄りのバランス。上・右でプレッシャーをかける。',
        description_en = 'Aggressive balance—applies pressure from the top and right.',
        no = 5,
    },
    {
        card_id = 'tcg_s_aqua_shield',
        name = '深水の盾艇',
        rank = 'S',
        type = 'free',
        stat_top = 5,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_ch_006.png',
        description = '下方向をやや厚くした防衛型。',
        description_en = 'Slightly thicker downward—leans defensive.',
        no = 6,
    },
    {
        card_id = 'tcg_s_wind_runner',
        name = '疾風の斥候',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_ch_007.png',
        description = '機動力重視。上辺からの奇襲に。',
        description_en = 'Mobility-focused—strikes along the top edge.',
        no = 7,
    },
    {
        card_id = 'tcg_s_stone_wall',
        name = '磐石の守人',
        rank = 'S',
        type = 'free',
        stat_top = 4,
        stat_right = 8,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_ch_008.png',
        description = '右辺特化の盾。横並びの奪取に強い。',
        description_en = 'Right-side shield—strong in sideways trades.',
        no = 8,
    },
    {
        card_id = 'tcg_a_iron_spike',
        name = '鉄棘の番人',
        rank = 'A',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_ch_009.png',
        description = '堅実なオールラウンダー。',
        description_en = 'Reliable all-rounder.',
        no = 9,
    },
    {
        card_id = 'tcg_a_shadow_cat',
        name = '影歩きの猫盗賊',
        rank = 'A',
        type = 'free',
        stat_top = 6,
        stat_right = 4,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_ch_010.png',
        description = '上と左右のバランス取り。隙を突く動き向き。',
        description_en = 'Balanced top and sides—looks for angles.',
        no = 10,
    },
    {
        card_id = 'tcg_a_holy_moth',
        name = '燐火の聖蛾',
        rank = 'A',
        type = 'free',
        stat_top = 4,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_001.png',
        description = '右への伸びで軽く有利を取る。',
        description_en = 'Reaches right for a slight advantage.',
        no = 11,
    },
    {
        card_id = 'tcg_a_rust_golem',
        name = '錆鉄の小ゴーレム',
        rank = 'A',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_002.png',
        description = '地味だが角で事故を減らす。',
        description_en = 'Plain but helps avoid corner disasters.',
        no = 12,
    },
    {
        card_id = 'tcg_b_moss_sprite',
        name = '苔森のスプライト',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_003.png',
        description = '完全バランスの凡庸カード。',
        description_en = 'Perfectly even stats—a filler staple.',
        no = 13,
    },
    {
        card_id = 'tcg_b_cave_bat',
        name = '洞窟コウモリ',
        rank = 'B',
        type = 'free',
        stat_top = 5,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_004.png',
        description = '上だけ突出した奇襲役。',
        description_en = 'Top-heavy surprise striker.',
        no = 14,
    },
    {
        card_id = 'tcg_b_mud_frog',
        name = '泥沼ガエル',
        rank = 'B',
        type = 'free',
        stat_top = 3,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_005.png',
        description = '右に振った火力。',
        description_en = 'Power shifted to the right.',
        no = 15,
    },
    {
        card_id = 'tcg_b_coal_imp',
        name = '炭坑インプ',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 3,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_006.png',
        description = '下が弱め。上でつなぐ前提。',
        description_en = 'Weak below—plan to link from the top.',
        no = 16,
    },
    {
        card_id = 'tcg_c_slime',
        name = 'グリーンスライム',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 3,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_007.png',
        description = 'どこも強くないが敷き詰めやすい。',
        description_en = 'Nowhere strong—easy slot filler.',
        no = 17,
    },
    {
        card_id = 'tcg_c_rat',
        name = '溝ネズミ',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 3,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_008.png',
        description = '上が弱い。下レーンでのつなぎ用。',
        description_en = 'Soft on top—bridging piece for the bottom lane.',
        no = 18,
    },
    {
        card_id = 'tcg_c_mushroom',
        name = '歩くキノコ',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 2,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_009.png',
        description = '右が穴場。逆に右からは狙われやすい。',
        description_en = 'Weak on the right—watch for attacks from that side.',
        no = 19,
    },
    {
        card_id = 'tcg_c_ghost_jelly',
        name = '幽霊クラゲ',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 2,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_010.png',
        description = '下・左にわずかな粘り。',
        description_en = 'A little staying power on bottom-left.',
        no = 20,
    },
}
