--- カードマスタ（起動時に DB へ UPSERT。数値は1〜10）
--- image_path は NUI 基準（html/ からの相対）。実ファイル: html/assets/cards/{character|monster}/
--- キャラ 22 + モンスター 39 = 計 61（no 1〜61）。画像は assets/cards/{character|monster}/tcg_<card_id>.jpg。type は shitei / free
--- 合計の目安: UR 28〜32, SS 24〜27, S 20〜23, A 16〜19, B 12〜15, C 8〜11
--- name_en / description_en: BOOK NUI 英語表示用（DB 列にシードされる）
TcgCardsMaster = {
    {
        card_id = 'tcg_ur_antares',
        name = '覇星アンタレス',
        name_en = 'Antares the Sovereign Star',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 8,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ur_antares.jpg',
        description = '四方位にほぼ隙がない絶対王者。デッキの柱に据えたい。',
        description_en = 'Nearly flawless on all four sides—the backbone of your deck.',
        no = 1,
    },
    {
        card_id = 'tcg_ur_void_edge',
        name = '虚空の刃鬼',
        name_en = 'Void Blade Oni',
        rank = 'UR',
        type = 'shitei',
        stat_top = 6,
        stat_right = 10,
        stat_bottom = 5,
        stat_left = 9,
        image_path = 'assets/cards/character/tcg_ur_void_edge.jpg',
        description = '右辺と左辺に極大火力。配置で脅威の脅威帯を形成する。',
        description_en = 'Huge power on left and right—placement builds a brutal horizontal threat.',
        no = 2,
    },
    {
        card_id = 'tcg_ss_silver_knight',
        name = '銀翼の聖騎士',
        name_en = 'Silverwing Paladin',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_ss_silver_knight.jpg',
        description = '上方向への突破力が高く、先攻配置に向く。',
        description_en = 'Strong upward punch—great when you place first.',
        no = 3,
    },
    {
        card_id = 'tcg_ss_moon_sage',
        name = '月虹の賢者',
        name_en = 'Moonbow Sage',
        rank = 'SS',
        type = 'shitei',
        stat_top = 6,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ss_moon_sage.jpg',
        description = '下・左を厚くし、盤面下角の確保に強い。',
        description_en = 'Thick toward bottom-left—locks down the lower corner.',
        no = 4,
    },
    {
        card_id = 'tcg_s_flame_fist',
        name = '烈火の拳士',
        name_en = 'Blazing Pugilist',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_s_flame_fist.jpg',
        description = '攻め寄りのバランス。上・右でプレッシャーをかける。',
        description_en = 'Aggressive balance—applies pressure from the top and right.',
        no = 5,
    },
    {
        card_id = 'tcg_s_aqua_shield',
        name = '深水の盾艇',
        name_en = 'Deepwater Bulwark',
        rank = 'S',
        type = 'free',
        stat_top = 5,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_s_aqua_shield.jpg',
        description = '下方向をやや厚くした防衛型。',
        description_en = 'Slightly thicker downward—leans defensive.',
        no = 6,
    },
    {
        card_id = 'tcg_s_wind_runner',
        name = '疾風の斥候',
        name_en = 'Galewind Scout',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_s_wind_runner.jpg',
        description = '機動力重視。上辺からの奇襲に。',
        description_en = 'Mobility-focused—strikes along the top edge.',
        no = 7,
    },
    {
        card_id = 'tcg_s_stone_wall',
        name = '磐石の守人',
        name_en = 'Bedrock Warden',
        rank = 'S',
        type = 'free',
        stat_top = 4,
        stat_right = 8,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_s_stone_wall.jpg',
        description = '右辺特化の盾。横並びの奪取に強い。',
        description_en = 'Right-side shield—strong in sideways trades.',
        no = 8,
    },
    {
        card_id = 'tcg_a_iron_spike',
        name = '鉄棘の番人',
        name_en = 'Iron Thorn Sentinel',
        rank = 'A',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_a_iron_spike.jpg',
        description = '堅実なオールラウンダー。',
        description_en = 'Reliable all-rounder.',
        no = 9,
    },
    {
        card_id = 'tcg_a_shadow_cat',
        name = '影歩きの猫盗賊',
        name_en = 'Shadowstep Cat Thief',
        rank = 'A',
        type = 'free',
        stat_top = 6,
        stat_right = 4,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_a_shadow_cat.jpg',
        description = '上と左右のバランス取り。隙を突く動き向き。',
        description_en = 'Balanced top and sides—looks for angles.',
        no = 10,
    },
    {
        card_id = 'tcg_a_holy_moth',
        name = '燐火の聖蛾',
        name_en = 'Witchfire Holy Moth',
        rank = 'A',
        type = 'free',
        stat_top = 4,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_a_holy_moth.jpg',
        description = '右への伸びで軽く有利を取る。',
        description_en = 'Reaches right for a slight advantage.',
        no = 11,
    },
    {
        card_id = 'tcg_a_rust_golem',
        name = '錆鉄の小ゴーレム',
        name_en = 'Rustiron Golemling',
        rank = 'A',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 5,
        image_path = 'assets/cards/character/tcg_a_rust_golem.jpg',
        description = '地味だが角で事故を減らす。',
        description_en = 'Plain but helps avoid corner disasters.',
        no = 12,
    },
    {
        card_id = 'tcg_b_moss_sprite',
        name = '苔森のスプライト',
        name_en = 'Mossgrove Sprite',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_moss_sprite.jpg',
        description = '完全バランスの凡庸カード。',
        description_en = 'Perfectly even stats—a filler staple.',
        no = 13,
    },
    {
        card_id = 'tcg_b_cave_bat',
        name = '洞窟コウモリ',
        name_en = 'Cavern Bat',
        rank = 'B',
        type = 'free',
        stat_top = 5,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_cave_bat.jpg',
        description = '上だけ突出した奇襲役。',
        description_en = 'Top-heavy surprise striker.',
        no = 14,
    },
    {
        card_id = 'tcg_b_mud_frog',
        name = '泥沼ガエル',
        name_en = 'Mire Frog',
        rank = 'B',
        type = 'free',
        stat_top = 3,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_mud_frog.jpg',
        description = '右に振った火力。',
        description_en = 'Power shifted to the right.',
        no = 15,
    },
    {
        card_id = 'tcg_b_coal_imp',
        name = '炭坑インプ',
        name_en = 'Colliery Imp',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 3,
        stat_left = 4,
        image_path = 'assets/cards/character/tcg_b_coal_imp.jpg',
        description = '下が弱め。上でつなぐ前提。',
        description_en = 'Weak below—plan to link from the top.',
        no = 16,
    },
    {
        card_id = 'tcg_c_slime',
        name = 'グリーンスライム',
        name_en = 'Green Slime',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 3,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_slime.jpg',
        description = 'どこも強くないが敷き詰めやすい。',
        description_en = 'Nowhere strong—easy slot filler.',
        no = 17,
    },
    {
        card_id = 'tcg_c_rat',
        name = '溝ネズミ',
        name_en = 'Gutter Rat',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 3,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_rat.jpg',
        description = '上が弱い。下レーンでのつなぎ用。',
        description_en = 'Soft on top—bridging piece for the bottom lane.',
        no = 18,
    },
    {
        card_id = 'tcg_c_mushroom',
        name = '歩くキノコ',
        name_en = 'Walking Mushroom',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 2,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_mushroom.jpg',
        description = '右が穴場。逆に右からは狙われやすい。',
        description_en = 'Weak on the right—watch for attacks from that side.',
        no = 19,
    },
    {
        card_id = 'tcg_c_ghost_jelly',
        name = '幽霊クラゲ',
        name_en = 'Ghost Jelly',
        rank = 'C',
        type = 'free',
        stat_top = 2,
        stat_right = 2,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/character/tcg_c_ghost_jelly.jpg',
        description = '下・左にわずかな粘り。',
        description_en = 'A little staying power on bottom-left.',
        no = 20,
    },
    {
        card_id = 'tcg_m_ur_reaper',
        name = '冥府の死神司祭ターナトス',
        name_en = 'Thanatos, High Priest of the Underworld',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 9,
        stat_left = 9,
        image_path = 'assets/cards/monster/tcg_m_ur_reaper.jpg',
        description = '紫炎を纏う大鎌で魂を刈り取る冥府の使徒。彼の通った跡には霊魂すら残らない。',
        description_en = 'An emissary of the underworld who reaps souls with a violet-flamed scythe. Not even spirits remain in his wake.',
        no = 21,
    },
    {
        card_id = 'tcg_m_ur_moon_goddess',
        name = '月夜の女神セレネ',
        name_en = 'Selene, Goddess of the Moonlit Night',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 9,
        stat_bottom = 8,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_ur_moon_goddess.jpg',
        description = '三日月の冠を戴き、銀の月杖で潮汐と夢を司る女神。月光の下で全ての傷は癒される。',
        description_en = 'A goddess crowned with the crescent, ruling tides and dreams with her silver moon-staff. All wounds are healed beneath her moonlight.',
        no = 22,
    },
    {
        card_id = 'tcg_m_ss_thunder_god',
        name = '雷霆神トールヴァル',
        name_en = 'Thorvall, God of Thunder',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_thunder_god.jpg',
        description = '白髭をなびかせ黄金鎧を纏う雷神。振り下ろす雷鎚は山を割り、嵐を呼ぶ。',
        description_en = 'A thunder god in golden armor with a billowing white beard. His descending hammer cleaves mountains and summons storms.',
        no = 23,
    },
    {
        card_id = 'tcg_m_ss_phoenix',
        name = '鎖縛の不死鳥イグニス',
        name_en = 'Ignis, the Chained Phoenix',
        rank = 'SS',
        type = 'shitei',
        stat_top = 8,
        stat_right = 8,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_phoenix.jpg',
        description = '黒鎧と鎖で力を封じられた炎の霊鳥。死しても灰から蘇り、千年の業火を撒き散らす。',
        description_en = 'A flame-spirit bird whose power is sealed by black armor and chains. Though slain, she rises from ashes to scatter a thousand-year inferno.',
        no = 24,
    },
    {
        card_id = 'tcg_m_ss_sea_goddess',
        name = '珊瑚の海神アクアリーネ',
        name_en = 'Aquarine, Goddess of the Coral Seas',
        rank = 'SS',
        type = 'shitei',
        stat_top = 7,
        stat_right = 8,
        stat_bottom = 7,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_ss_sea_goddess.jpg',
        description = '珊瑚の冠と貝殻の鎧を纏い、サンゴ三叉戟で潮流を操る海の女神。船乗りの祈りを聞き届ける。',
        description_en = 'A sea goddess in coral crown and shell armor, commanding currents with her coral trident. She heeds the prayers of sailors.',
        no = 25,
    },
    {
        card_id = 'tcg_m_s_sun_priest',
        name = '黄金の太陽神官ソルアレス',
        name_en = 'Solares, Priest of the Golden Sun',
        rank = 'S',
        type = 'free',
        stat_top = 8,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_s_sun_priest.jpg',
        description = '黄金の鎧と白マントを纏い炎槍を掲げる神官。彼が槍を天に向ければ太陽が応える。',
        description_en = 'A priest in golden armor and white mantle, raising a flame-spear. When he points it skyward, the sun answers his call.',
        no = 26,
    },
    {
        card_id = 'tcg_m_s_pharaoh_mummy',
        name = '古王国のファラオ・ミイラ',
        name_en = 'Pharaoh Mummy of the Old Kingdom',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_pharaoh_mummy.jpg',
        description = '青き炎の眼でアンク杖を握る王のミイラ。聖刻文字の呪いは三千年の時を超えて生者を縛る。',
        description_en = 'A royal mummy with eyes of blue flame, gripping an ankh-staff. His hieroglyphic curse binds the living across three millennia.',
        no = 27,
    },
    {
        card_id = 'tcg_m_s_dark_witch',
        name = '暗黒の角持ち魔女モルガナ',
        name_en = 'Morgana, the Horned Dark Witch',
        rank = 'S',
        type = 'free',
        stat_top = 8,
        stat_right = 7,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_dark_witch.jpg',
        description = '黒髪に角を生やし髑髏杖を振るう魔女。紫炎の呪文は敵の影を縫い止め、抜け出させない。',
        description_en = 'A witch with black hair and horns, brandishing a skull-staff. Her violet-flame hex pins enemies by their own shadows.',
        no = 28,
    },
    {
        card_id = 'tcg_m_s_forest_spirit',
        name = '深森の樹霊フローラ',
        name_en = 'Flora, Spirit of the Deep Forest',
        rank = 'S',
        type = 'free',
        stat_top = 6,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_s_forest_spirit.jpg',
        description = '緑髪に花冠、蝶を従える森の精霊。彼女が踏みしめた地には一夜で花が咲き乱れる。',
        description_en = 'A forest spirit with green hair, a flower crown, and butterflies in her train. Where she steps, blossoms bloom in a single night.',
        no = 29,
    },
    {
        card_id = 'tcg_m_a_demon_warlord',
        name = '赤肌の魔将バルガス',
        name_en = 'Balgus, the Crimson Warlord',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_a_demon_warlord.jpg',
        description = '赤き肌に巻角を持つ魔族の将。両手大斧の一振りは、敵陣の隊列ごと薙ぎ払う。',
        description_en = 'A demon warlord with crimson skin and curling horns. A single swing of his great axe sweeps away entire battle lines.',
        no = 30,
    },
    {
        card_id = 'tcg_m_a_blood_berserker',
        name = '血染めの戦鬼ガルム',
        name_en = 'Garm, the Blood-Soaked Berserker',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_a_blood_berserker.jpg',
        description = '烏旗を背負い双剣で踊るように戦う狂戦士。返り血を浴びるほど剣速が増す。',
        description_en = 'A berserker who dances with twin blades beneath a raven banner. The more blood he is bathed in, the faster his swords become.',
        no = 31,
    },
    {
        card_id = 'tcg_m_a_flame_valkyrie',
        name = '紅蓮の戦姫イグニフィア',
        name_en = 'Ignifia, the Crimson Valkyrie',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_a_flame_valkyrie.jpg',
        description = '赤髪と紅鎧を纏い双炎刀を振るう戦姫。彼女の通った戦場は灰しか残らない。',
        description_en = 'A valkyrie in crimson armor with flowing red hair, wielding twin flame-blades. Only ashes remain on the battlefield she crosses.',
        no = 32,
    },
    {
        card_id = 'tcg_m_a_medusa',
        name = '蛇髪の魔女メデューサ',
        name_en = 'Medusa, the Serpent-Haired Witch',
        rank = 'A',
        type = 'free',
        stat_top = 6,
        stat_right = 6,
        stat_bottom = 5,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_a_medusa.jpg',
        description = '蛇の髪を蠢かせ青銅の曲刀を持つ呪われた美女。その眼を見た者は石となる。',
        description_en = 'A cursed beauty with writhing serpents for hair, gripping a bronze curved blade. Those who meet her gaze are turned to stone.',
        no = 33,
    },
    {
        card_id = 'tcg_m_a_minotaur',
        name = '迷宮の牛頭ミノタウロス',
        name_en = 'Minotaur of the Labyrinth',
        rank = 'A',
        type = 'free',
        stat_top = 7,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_a_minotaur.jpg',
        description = '黒角と棘鎧を纏い両手戦斧を振るう半人半牛の怪物。怒れば迷宮の壁すら砕く。',
        description_en = 'A half-bull beast in black horns and spiked armor, wielding a great battle-axe. In rage, even the labyrinth walls shatter before him.',
        no = 34,
    },
    {
        card_id = 'tcg_m_b_stone_golem',
        name = '古代遺跡のストーンゴーレム',
        name_en = 'Ancient Ruin Stone Golem',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 5,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_b_stone_golem.jpg',
        description = '苔生した岩肌に青いルーンを刻まれた巨人。命令を忘れ、千年遺跡を守り続ける。',
        description_en = 'A giant of mossy stone inscribed with glowing blue runes. Long having forgotten its orders, it has guarded the ruins for a thousand years.',
        no = 35,
    },
    {
        card_id = 'tcg_m_b_war_bear',
        name = '戦化粧の熊神獣ウルサ',
        name_en = 'Ursa, the War-Painted Bear-Beast',
        rank = 'B',
        type = 'free',
        stat_top = 6,
        stat_right = 4,
        stat_bottom = 5,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_b_war_bear.jpg',
        description = '骨鎧と赤い戦化粧を纏う熊の神獣。北方部族の守護獣として崇められる。',
        description_en = 'A divine bear-beast in bone armor and red war-paint. The northern tribes revere her as their guardian beast.',
        no = 36,
    },
    {
        card_id = 'tcg_m_b_werewolf',
        name = '満月の人狼ファング',
        name_en = 'Fang, the Full-Moon Werewolf',
        rank = 'B',
        type = 'free',
        stat_top = 5,
        stat_right = 5,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_b_werewolf.jpg',
        description = '灰毛に革ベルト、無数の傷跡を持つ獣人。満月の夜のみ理性を失い、最も速くなる。',
        description_en = 'A beastman of grey fur, leather harness, and countless scars. Only on full-moon nights does he lose reason and become his swiftest.',
        no = 37,
    },
    {
        card_id = 'tcg_m_b_crystal_golem',
        name = '蒼晶の核ゴーレム',
        name_en = 'Azure Crystal Core Golem',
        rank = 'B',
        type = 'free',
        stat_top = 4,
        stat_right = 5,
        stat_bottom = 5,
        stat_left = 5,
        image_path = 'assets/cards/monster/tcg_m_b_crystal_golem.jpg',
        description = '胸の青き核から虹色の光を放つ結晶巨人。砕かれた破片すら攻撃する意志を持つ。',
        description_en = 'A crystal golem emitting rainbow light from the azure core in its chest. Even its shattered shards retain the will to attack.',
        no = 38,
    },
    {
        card_id = 'tcg_m_c_carrion_raven',
        name = '腐肉漁りの大鴉人',
        name_en = 'Carrion-Feasting Ravenfolk',
        rank = 'C',
        type = 'free',
        stat_top = 4,
        stat_right = 4,
        stat_bottom = 3,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_c_carrion_raven.jpg',
        description = '赤く濁った眼と皮革の装具を身に着けた鴉人。死体の山を漁って生きる墓場の守人。',
        description_en = 'A ravenfolk with cloudy red eyes and leather harness. He scavenges among corpses, a graveyard\'s unwelcome custodian.',
        no = 39,
    },
    {
        card_id = 'tcg_m_c_armored_slime',
        name = '錆鎧をまとった巨大スライム',
        name_en = 'Rust-Armored Greater Slime',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 4,
        image_path = 'assets/cards/monster/tcg_m_c_armored_slime.jpg',
        description = '戦死者の錆びた鎧片を体内に取り込んだ緑色の粘体。柔らかい体は刃を弾き、鎧片は牙となる。',
        description_en = 'A green ooze that has absorbed the rusted armor of fallen warriors. Its soft body deflects blades while the armor shards become its fangs.',
        no = 40,
    },
    {
        card_id = 'tcg_m_c_rot_zombie',
        name = '腐肉の屍喰鬼ロット',
        name_en = 'Rot, the Putrid Ghoul',
        rank = 'C',
        type = 'free',
        stat_top = 3,
        stat_right = 3,
        stat_bottom = 4,
        stat_left = 3,
        image_path = 'assets/cards/monster/tcg_m_c_rot_zombie.jpg',
        description = '緑灰の腐肉と腫物だらけの屍。垂れ下がった腕で獲物を引き寄せ、伝染性の毒を撒き散らす。',
        description_en = 'A corpse covered in green-grey rot and pustules. With his dangling arms he drags victims close, spreading contagious venom.',
        no = 41,
    },
    {
        card_id = 'tcg_ss_lion_paladin',
        name = '獅心の聖騎士レオンハルト',
        name_en = 'Leonhardt, Lionheart Paladin',
        rank = 'SS',
        type = 'shitei',
        stat_top = 8,
        stat_right = 8,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/character/tcg_ss_lion_paladin.jpg',
        description = '王家の獅子紋を胸に刻む銀甲の騎士。聖なる金光を纏う長剣で闇を切り裂く。',
        description_en = 'A silver knight bearing the royal lion crest. His longsword shines with holy light that cuts through darkness.',
        no = 42,
    },
    {
        card_id = 'tcg_s_runic_ranger',
        name = '森弓の狩人シルヴィア',
        name_en = 'Sylvia, Runic Forest Hunter',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 7,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/character/tcg_s_runic_ranger.jpg',
        description = '刻印弓と緑のマントをまとった斥候。弓身のルーンが矢筋に魔力を宿す。',
        description_en = 'A scout in green cloak with a rune-carved bow. Sigils along the limbs imbue every shot.',
        no = 43,
    },
    {
        card_id = 'tcg_m_ur_vampire_lord',
        name = '深紅の貴公子ヴラド',
        name_en = 'Vlad, the Crimson Noble',
        rank = 'UR',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 8,
        stat_left = 9,
        image_path = 'assets/cards/monster/tcg_m_ur_vampire_lord.jpg',
        description = '漆黒の礼服に蝙蝠を従え、銀杯には永劫の渇きが注がれる。細剣の先には優雅な死が舞う。',
        description_en = 'A vampire aristocrat in black finery, bats at his back and a silver goblet raised. His rapier delivers an elegant death.',
        no = 44,
    },
    {
        card_id = 'tcg_m_ur_void_archdemon',
        name = '虚空千眼の魔神アザゾート',
        name_en = 'Azazoth, Thousand-Eyed Void Archdemon',
        rank = 'UR',
        type = 'shitei',
        stat_top = 10,
        stat_right = 8,
        stat_bottom = 7,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_ur_void_archdemon.jpg',
        description = '六腕と無数の瞳を持つ深淵の化身。紫水晶の杖は狭間を裂き、幽魂を使役する。',
        description_en = 'A six-armed abyssal avatar whose eyes pierce every veil. His crystal staff tears the veil and binds wandering spirits.',
        no = 45,
    },
    {
        card_id = 'tcg_m_ur_rune_colossus',
        name = '蒼刻の古代巨像',
        name_en = 'Ancient Colossus of Azure Runes',
        rank = 'UR',
        type = 'shitei',
        stat_top = 8,
        stat_right = 9,
        stat_bottom = 9,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ur_rune_colossus.jpg',
        description = '失われた墟が意志を持って歩む巨像。胸部の核が蒼光を放ち、巨岩の棍棒で大地を砕く。',
        description_en = 'Ruins given motion—a walking colossus whose chest core bursts cyan light, crushing earth with a monolithic stone club.',
        no = 46,
    },
    {
        card_id = 'tcg_m_ss_steam_colossus',
        name = '魔導蒸気兵ギガント・フォージ',
        name_en = 'Gigant Forge, Magitek Steam Colossus',
        rank = 'SS',
        type = 'shitei',
        stat_top = 8,
        stat_right = 7,
        stat_bottom = 8,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_steam_colossus.jpg',
        description = '錆鉄と蒸気機関が融合した守護兵。右腕の巨槌と左腕の回転ドリルが要塞を粉砕する。',
        description_en = 'A guardian of rusted iron and steam. Its war hammer and drill-arm demolish fortifications.',
        no = 47,
    },
    {
        card_id = 'tcg_m_ss_crimson_dragon',
        name = '紅蓮の古龍カルナーク',
        name_en = 'Karnark, the Crimson Ancient Dragon',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_crimson_dragon.jpg',
        description = '紅蓮の鱗と煤けた翼を持つ直立竜。吐息は岩を溶かし、尾刃は戦列を薙ぐ。',
        description_en = 'A bipedal wyrm of crimson scales and soot-dark wings. Its breath melts stone; its bladed tail sweeps battle lines.',
        no = 48,
    },
    {
        card_id = 'tcg_m_ss_succubus_queen',
        name = '淫魔女王アスタライズ',
        name_en = 'Astalyze, Queen of Lust Demons',
        rank = 'SS',
        type = 'shitei',
        stat_top = 7,
        stat_right = 8,
        stat_bottom = 8,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_succubus_queen.jpg',
        description = '漆黒の鞭と茨冠を戴く魔界の女王。妖瞳に捕らわれた者は魂ごと奪われるという。',
        description_en = 'The demon queen of jet whips and thorn crowns. Those who meet her gaze lose their souls.',
        no = 49,
    },
    {
        card_id = 'tcg_m_ss_inferno_demon_king',
        name = '業炎魔王ベルゼゴル',
        name_en = 'Belzegor, Inferno Demon King',
        rank = 'SS',
        type = 'shitei',
        stat_top = 9,
        stat_right = 8,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_ss_inferno_demon_king.jpg',
        description = '骸冠と炎魔剣を携えた魔界の覇者。翼からは灰が舞い、大地は灼熱に割れる。',
        description_en = 'A demon overlord crowned in bone, greatsword wreathed in hellfire. Ash falls from his wings; the earth splits with heat.',
        no = 50,
    },
    {
        card_id = 'tcg_m_ss_arcane_grimoire',
        name = '紫苑の大魔導士エレノア',
        name_en = 'Eleanor, Grand Sorceress of Amethyst',
        rank = 'SS',
        type = 'shitei',
        stat_top = 7,
        stat_right = 8,
        stat_bottom = 8,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_ss_arcane_grimoire.jpg',
        description = '金刺繍の法衣と魔導書を携えた宮廷最高位魔導師。翻る頁から星屑の術式が溢れ出す。',
        description_en = 'A court archmage in gold-threaded robes with an open grimoire—constellations spill from every turning page.',
        no = 51,
    },
    {
        card_id = 'tcg_m_ss_necro_matron',
        name = '漆黒の死霊妃モルヴェイン',
        name_en = 'Morveine, Matron of the Dead',
        rank = 'SS',
        type = 'shitei',
        stat_top = 8,
        stat_right = 7,
        stat_bottom = 8,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_ss_necro_matron.jpg',
        description = '黒肌のダークエルフにして高位ネクロマンサー。紫水晶の杖先で影が生者を縛る。',
        description_en = 'A dark elf necromancer high lady. Purple crystal staff-tip binds the living with crawling shadow.',
        no = 52,
    },
    {
        card_id = 'tcg_m_ss_lich_overlord',
        name = '冥冠のリッチロードオルセウス',
        name_en = 'Ortheus, Crowned Lich Overlord',
        rank = 'SS',
        type = 'shitei',
        stat_top = 8,
        stat_right = 9,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_ss_lich_overlord.jpg',
        description = '緑の邪炎を眼窩に宿す不死の王。召喚陣の上に立ち、顎骨杖で死者の軍勢を呼ぶ。',
        description_en = 'An undead king with green witchfire in his sockets. He stands on a summoning circle, calling legions with a skull-topped staff.',
        no = 53,
    },
    {
        card_id = 'tcg_m_s_light_phantom',
        name = '光の守護幻影ライオット',
        name_en = 'Lyott, Phantom Guardian of Light',
        rank = 'S',
        type = 'free',
        stat_top = 8,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_s_light_phantom.jpg',
        description = '信仰が凝縮して宿った聖騎士の幻影。実体は乏しいが、その一撃だけは本物と変わらない。',
        description_en = 'A paladin-shaped mirage born of faith. Fleeting form—yet the strike lands as true steel.',
        no = 54,
    },
    {
        card_id = 'tcg_m_s_crystal_oracle',
        name = '蒼晶のハイエルフ神託者セレスタ',
        name_en = 'Selesta, High Elf Oracle of Crystal',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 7,
        stat_bottom = 8,
        stat_left = 8,
        image_path = 'assets/cards/monster/tcg_m_s_crystal_oracle.jpg',
        description = '銀髪と蒼水晶の杖を携えた高位エルフ。静かな瞳に未来の欠片が映る。',
        description_en = 'A high elf of silver hair and a staff of blue crystals—fragments of tomorrow glimmer in calm eyes.',
        no = 55,
    },
    {
        card_id = 'tcg_m_s_livingwood_archer',
        name = '森芽のエルフ射手リアンナ',
        name_en = 'Lianna, Livingwood Elf Archer',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_livingwood_archer.jpg',
        description = '生きた枝から成る弓を引く森の射手。緑箭は芽吹き、獲物の足止めとなる。',
        description_en = 'She draws a bow grown from living branch. Green-fletched arrows sprout roots that halt prey.',
        no = 56,
    },
    {
        card_id = 'tcg_m_s_mirror_ranger',
        name = '鏡写しの幻影狩人ミレイユ',
        name_en = 'Mireille, Mirror-Glass Phantom Hunter',
        rank = 'S',
        type = 'free',
        stat_top = 6,
        stat_right = 8,
        stat_bottom = 6,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_mirror_ranger.jpg',
        description = '水面に映った狩人の残像。ルーン弓は本体よりも角度だけ鋭い。',
        description_en = 'A hunter reflected one heartbeat late. Her rune-bow picks crueler angles than its living twin.',
        no = 57,
    },
    {
        card_id = 'tcg_m_s_nightshade_assassin',
        name = '夜刃のダークエルフナイトヴェイル',
        name_en = 'Nightveil, Dark Elf Blade of Nightshade',
        rank = 'S',
        type = 'free',
        stat_top = 6,
        stat_right = 7,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_nightshade_assassin.jpg',
        description = '双曲刃と紫の残映を操る暗殺者。音より速く、影より薄く踏み込む。',
        description_en = 'Twin curved blades and violet afterimages. She steps thinner than shadow and faster than sound.',
        no = 58,
    },
    {
        card_id = 'tcg_m_s_dusk_spellblade',
        name = '黄昏の呪剣士シャード',
        name_en = 'Shard, Spellblade of Dusk',
        rank = 'S',
        type = 'free',
        stat_top = 7,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_s_dusk_spellblade.jpg',
        description = '銀装のダークエルフ戦士。片手に紫刀、もう片手に術式を携え、刃と呪文を同時に叩き込む。',
        description_en = 'A dark elf spellblade in silvered plate—purple steel in one hand, a weaving hex in the other.',
        no = 59,
    },
    {
        card_id = 'tcg_m_s_storm_dragonkin',
        name = '紫電の竜人グラヴェル',
        name_en = 'Gravel, Storm Dragonkin',
        rank = 'S',
        type = 'free',
        stat_top = 8,
        stat_right = 6,
        stat_bottom = 6,
        stat_left = 7,
        image_path = 'assets/cards/monster/tcg_m_s_storm_dragonkin.jpg',
        description = '黒曜の鱗と雷翼を持つ二足竜人。裂帛の紫電が鎧の縫い目を走る。',
        description_en = 'A bipedal drake of obsidian scales and storm wings—violet lightning stitches every seam of his armor.',
        no = 60,
    },
    {
        card_id = 'tcg_m_a_blue_runeweaver',
        name = '蒼炎魔典のエルフ術師ミリア',
        name_en = 'Miria, Blue-Flame Elven Runeweaver',
        rank = 'A',
        type = 'free',
        stat_top = 6,
        stat_right = 6,
        stat_bottom = 7,
        stat_left = 6,
        image_path = 'assets/cards/monster/tcg_m_a_blue_runeweaver.jpg',
        description = '蒼炎と魔導書を織り合わせる若き術師。術式は未完成だが勢いだけは一流。',
        description_en = 'A young mage weaving azure flame with runes. Her forms are rough—her tempo is first-class.',
        no = 61,
    },
}
